"apiVersion": "v1"
"clusters":
- "cluster":
    "certificate-authority-data": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1USXhOREV6TVRjeU1Wb1hEVE15TVRJeE1URXpNVGN5TVZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTGc3CldZSGtrRFlKVGVpR0ExaFNyMm9FcWtQL0pCejBKSnhQSXk4NTZkZ3JJbk5BZlRSY0hWOHRNeHh3Q21pTW4rTEQKaENrd1BYTldvdzNGZ0g0ai9nRGI5NjNRQWhDdVRycVhBL3VpU2FlL09OT3FxSi9id2RoWDZZc0NzQlJ0d2xFNApSRWFneXpuYVhVWmJZTVNRV1VGOWZqVGRPT2VxMGk2OWNweFpoa0x4RXRaanRaT050Z044UGxsVTBGbWVFWWh0CmhSdllQZmxsT1ZWQWVlSjE0MjJyRXVyekFOOTJrdDBwNXJiV0lkMUlzNXA4bnYvZEJxVExUSm10dFAwZHJhdVUKUE1Kb1BNU25OY0I0TEtCTlc1N0g2U2tubE5vZlFvYkwyUWx0bG80Z2JiK29DWklnbzhHUHNPd0ZqMFJPUkduNwpnZFZRQ0ZkRk1wRW9obWZsMm5VQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZMTlNlNDFkaEJtYSsyUHZHdE9pcm9rMGJ6ZmdNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSXp0YmJjUStoQnM0a0JWV090egpPRjBrV3ROaWY1Yzd2TEo4QXkvYThaSFZzZVdpUU9xdkJPTHd3aEJWb01lQVFLNExCK3hvYmZublM4Ni9qSm90CmZ1MWlUQVBwMDFpemZBZ3VpNVBUYWd3ZTUwOTN0VGhDQnAvTWRmd0d0MjlHL0JaR1BHM3IvT21jSDdUNzhTTmgKMTFnc0dCRitsSDF4ZTNrZ3NiSzhIWjR0MzZRTUdZd3oyRlFUTjI2UXcwQ1JaSy9MUDQ0S3A5bWxITDRTYWQxQgpDbHA4NlRDSjc5eGc3RDUxUWdiVll1eDVnSjgvL1Q2MG1lNWx4T1dXUWJVWUhKNHlTczVuT3FuMy8rbS8vRlp1CjBnOXpSVE9YVGdkSjdmRXJHN2Y1bWhUL0NLQ2E0SnlKdyt1WDI2eHdURVJ1eTY3UkFRK3VkTlB1RW9ieFRwL1IKaHQwPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
    "server": "https://C54F9348292BEE2ED2B6642BECC6B6F9.gr7.us-west-2.eks.amazonaws.com"
  "name": "arn:aws:eks:us-west-2:039956293909:cluster/managed-airflow-mwaa"
"contexts":
- "context":
    "cluster": "arn:aws:eks:us-west-2:039956293909:cluster/managed-airflow-mwaa"
    "user": "mwaa"
  "name": "mwaa"
"current-context": "mwaa"
"kind": "Config"
"users":
- "name": "mwaa"
  "user":
    "exec":
      "apiVersion": "client.authentication.k8s.io/v1beta1"
      "args":
      - "--region"
      - "us-west-2"
      - "eks"
      - "get-token"
      - "--cluster-name"
      - "managed-airflow-mwaa"
      "command": "aws"
