"apiVersion": "v1"
"clusters":
- "cluster":
    "certificate-authority-data": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1USXhOVEU1TlRVek9Wb1hEVE15TVRJeE1qRTVOVFV6T1Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTnRwCnZjWkx5WExLRFA0dDlIN28zSkxnWlJ3cU9HdFNBR3d4Tlord3lrcmNDNzBVU1FYc1FVeUJNWU5XcXd3TThiS0QKcTR6SWhhak9paFFGRUUwTC9XdWpNK2FlZmt2ZlUxQlJjZEFvMUZtTWxkRzQyb043NEMwMGtYU1dpMjJYa2RtWQpuRlZwb25vMWFxb2ZoL3JYRVBheVJ2dE5nZ1NmeVkxWVdabDRDcDUyS2xROFV0ZmEzUGZNN212VHJURFBQdWdYCmc1c2NiaGlnU0cxWE4zczFSR0s4dzNkWm5ZVjg0cHBteWhPc2JxcFpZYlZZTXBGSUlYR1l0UmN5SlcvaHRoNFQKemdjdXh3SXFyUVlXQVE5ejdpOWNzdXd2T0dOUU43SXlGOHV2L0V5VG1qcUwxV3E4RS96N0FieDVwTklNQUhWRQp5b29BRnFZeE9IQWY1NjJDSTdrQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZQL2JreDRCbUt4UVNUWUpOZXQ2VXZ5WWplTEpNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSmZJbTZBUEFHajVPUDdLdnJvagpRemJSd2FQd2xCcDE5bWRyMm1VYWNrUWEwV05kSVgvN2FQV29IVVg3c3FTKzQ1V1FNRmZIT2FRR1FDNWY1MVM4Ck8wOXdSOGxZUmxZNEsyNms0ZmpsZ1MzSDlDNEhINHNEVC9XcHVjbENGc2ZZVmNKUFpvcGF1MTNrOFd6KzV0RnEKd2Z4S2NlNWJwaFFlMGViRlAvRmh6NnRwbTVMVGk5WlJDVHBUZURPVkRIbGpSVGlKNnNES2JhNU9nY2FJaG43SwppaGRGVERYWHVuV2o0ZkNKU1p0SkVydWRHbmxvTnIrRUNZb1JYd2diK0hwVUV5TnBzTktPNm5nRzJTSFhpZmh6CnZhOEFFdFRpOVkwNTlYa1hXWWhnVVUxZUs1R1BwdFJUeS8zcUFXcm9ST0YzZHZna0w3UFRXdnkzRnpmWWdMRWIKbnhVPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
    "server": "https://1AE4CB5B6F503D9DFEC54F3291721393.gr7.us-west-2.eks.amazonaws.com"
  "name": "arn:aws:eks:us-west-2:190781341368:cluster/managed-airflow-mwaa"
"contexts":
- "context":
    "cluster": "arn:aws:eks:us-west-2:190781341368:cluster/managed-airflow-mwaa"
    "user": "mwaa"
  "name": "mwaa"
"current-context": "mwaa"
"kind": "Config"
"users":
- "name": "mwaa"
  "user":
    "exec":
      "apiVersion": "client.authentication.k8s.io/v1beta1"
      "args":
      - "--region"
      - "us-west-2"
      - "eks"
      - "get-token"
      - "--cluster-name"
      - "managed-airflow-mwaa"
      "command": "aws"
