"apiVersion": "v1"
"clusters":
- "cluster":
    "certificate-authority-data": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1USXhOVEF3TVRBeE9Gb1hEVE15TVRJeE1qQXdNVEF4T0Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTXM2Cjg1RUJ4RWcrVmh0VUc1eWVpZXlxUTBGU0ZKMTg0ZXlBN1hWRWhIblpzYWI4YkxsUEJBUVprVS85b1BqNnFiU3IKcGtpWDc4KzA5OGo3ZWpNclhzL1pYeFpzY0NBRENhQ0RGR0N2Y0U3aHorOC9WT3UycG53OHlGMjhQNFJNL3RMawpOZVBQN1ozdVNhNDVlR1N1dy9MZ0xpUC9SVkw5M04wam5lMWZmSGVuRzN4MFJ4UVNxZWUyZndjd3h3OWxURHZ1CjBhQzIyT2NsUDNyMTlVcEg5SnZWNnlMdUUrTUxWWHB2UzdRRjdPa0tiakpVaHo0OW5UQVZiSk1VRTBHUEtxL04KRGxudHlNSGxhdHllajdCVXBhT0t4MWNzMmtwdW9raW93c2g0TldKc2VVTmU4S1EwV25KcXFiRGU2SHN5VEkyawpEMUh1WWEzd01FQUgyd05RTVNzQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZQOXJOUlJlSjN4SG9KQ3Q4VW15SEdWbDAvazNNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRm5td1RCVXZ6QUxpdjNreXFYSgpRWHFzZjhTeWF2blFrQlpOTkRneG42Y3B6L0RTT0JKOWhvZUl6VnZDaHZabStWOWQwaWZxNEFsSFRWTENhN1JrClFWanpHdVYvbk42ZHorbDY1Ti9zVHNCOGt2MVhJWWtyZVlIaHIxbko4dnZLQ25NQURGajhrd0JROWZ0TmhMQlIKaEkzc3cwMU1MSFNmdkxCZjVzM1k1dTA0U3BGVVh6eCtNQ05Sam5sdWp0VjV3YS9tUVdsSndtNUg5bXhrZGd3ZwpWd1pDUjYwMmE0b3ZrSWxLYllOalA3cXkySW9vNjg2a2RTejh4Vzc5TGpLM0hrN2t1S2hpRXd5OGRoS0dGR25xCkczbFplVFE2WjErUUw4bmlxdEFXOHpwcUFQaXdqbi96bmFWQ3pBTGpYVDVWVXNDR3FtTTg0M280bXMwQkZGQzQKdUtRPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
    "server": "https://31900705F6C644F27983252C270A1311.gr7.us-west-2.eks.amazonaws.com"
  "name": "arn:aws:eks:us-west-2:859006846143:cluster/managed-airflow-mwaa"
"contexts":
- "context":
    "cluster": "arn:aws:eks:us-west-2:859006846143:cluster/managed-airflow-mwaa"
    "user": "mwaa"
  "name": "mwaa"
"current-context": "mwaa"
"kind": "Config"
"users":
- "name": "mwaa"
  "user":
    "exec":
      "apiVersion": "client.authentication.k8s.io/v1beta1"
      "args":
      - "--region"
      - "us-west-2"
      - "eks"
      - "get-token"
      - "--cluster-name"
      - "managed-airflow-mwaa"
      "command": "aws"